FROM apache/airflow:3.1.3

USER root 
RUN apt-get update && apt-get install -y vim 
USER airflow
ADD requirements_airflow.txt .

RUN pip install apache-airflow==${AIRFLOW_VERSION} -r requirements_airflow.txt


