services:
 
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "9464:9464"   # Prometheus metrics endpoint
    depends_on:
      - loki
      - tempo

  prometheus:
    image: prom/prometheus:latest
    mem_limit: 400m
    memswap_limit: 600m
    cpus: "0.5"
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=3d"
      - "--query.max-concurrency=2"
    restart: unless-stopped
    
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo/config.yaml
    volumes:
      - ./tempo-config.yaml:/etc/tempo/config.yaml
    ports:
      - "3200:3200"
  

  grafana:
    image: grafana/grafana:latest
    mem_limit: 200m
    cpus: "0.5"
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_LEVEL=warn
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki
      - tempo

  networks:
    default:
      name: observability-net