name: Lint
description: Setup Python + Poetry and run lint

inputs:
  python-version:
    required: true
  poetry-version:
    required: true

runs: 
  using: composite 
  steps: 
    - uses: action/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: ${{ inputs.python-version }}

    - name: Setup Poetry
      uses: abatilo/actions-poetry@v3
      with: 
        poetry-version: ${{ inputs.poetry-version }}

    - name: Configure Poetry
      run: poetry config virtualenvs.in-project true
    
    - name: Cache Poetry 
      uses: actions/cache@v3
      with:
        path: | 
          ~/.cache/pypoetry
          ~/.cache/pip 
          .venv 
        key: poetry-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.poetry-version }}-${{ hashFiles('poetry.lock') }}
        
    - name: Install dependencies
      run: | 
        poetry install --only test --no-interaction --no-ansi
    
    - name: Check Linting
      run: make check