"""removed unncessary index.

Revision ID: 07d0bddcda20
Revises: fa5016dc4969
Create Date: 2026-03-11 15:35:53.306020

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07d0bddcda20"
down_revision: Union[str, Sequence[str], None] = "fa5016dc4969"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_paper_processing_states_paper_id"),
        table_name="paper_processing_states",
    )
    op.create_unique_constraint(None, "paper_processing_states", ["paper_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "paper_processing_states", type_="unique")
    op.create_index(
        op.f("ix_paper_processing_states_paper_id"),
        "paper_processing_states",
        ["paper_id"],
        unique=True,
    )
    # ### end Alembic commands ###
