"""update domain name type and add comments.

Revision ID: 3b9f0efd76ba
Revises: 221b80d2b098
Create Date: 2026-02-08 23:02:23.704496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3b9f0efd76ba"
down_revision: Union[str, Sequence[str], None] = "221b80d2b098"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "domains",
        "code",
        existing_type=sa.VARCHAR(length=25),
        type_=sa.Text(),
        existing_comment="Code for the domain, e.g., CS, Physics",
        existing_nullable=True,
    )
    op.alter_column(
        "domains",
        "datasource_id",
        existing_type=sa.UUID(),
        comment="ID of the data source (e.g., arXiv, PubMed)",
        existing_nullable=False,
    )
    op.alter_column(
        "domains",
        "name",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_comment="Name of the domain, e.g., Computer Science, Physics",
        existing_nullable=False,
    )
    op.alter_column(
        "papers",
        "abstract",
        existing_type=sa.TEXT(),
        comment="Abstract of the paper",
        existing_nullable=False,
    )
    op.alter_column(
        "subjects",
        "code",
        existing_type=sa.VARCHAR(length=25),
        type_=sa.Text(),
        existing_comment="Code for the primary subject, e.g., CS, Physics",
        existing_nullable=False,
    )
    op.alter_column(
        "subjects",
        "name",
        existing_type=sa.VARCHAR(length=25),
        type_=sa.Text(),
        existing_comment="Name of the primary subject, e.g., Physics",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subjects",
        "name",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=25),
        existing_comment="Name of the primary subject, e.g., Physics",
        existing_nullable=False,
    )
    op.alter_column(
        "subjects",
        "code",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=25),
        existing_comment="Code for the primary subject, e.g., CS, Physics",
        existing_nullable=False,
    )
    op.alter_column(
        "papers",
        "abstract",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Abstract of the paper",
        existing_nullable=False,
    )
    op.alter_column(
        "domains",
        "name",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_comment="Name of the domain, e.g., Computer Science, Physics",
        existing_nullable=False,
    )
    op.alter_column(
        "domains",
        "datasource_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="ID of the data source (e.g., arXiv, PubMed)",
        existing_nullable=False,
    )
    op.alter_column(
        "domains",
        "code",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=25),
        existing_comment="Code for the domain, e.g., CS, Physics",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
