"""revised db.

Revision ID: 5d6a01854542
Revises:
Create Date: 2026-03-08 01:22:21.033275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5d6a01854542"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier for the author"
        ),
        sa.Column(
            "name", sa.String(), nullable=False, comment="Full name of the author"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("name", name="uq_author_name"),
    )
    op.create_table(
        "datasources",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Unique identifier for the data source (e.g., arXiv, PubMed)",
        ),
        sa.Column("name", sa.String(), nullable=False, comment="Name of the source"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("name", name="uq_datasources_name"),
    )
    op.create_table(
        "domains",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Unique identifier for the academic domain",
        ),
        sa.Column(
            "code",
            sa.Text(),
            nullable=True,
            comment="Code for the domain, e.g., CS, Physics",
        ),
        sa.Column(
            "datasource_id",
            sa.UUID(),
            nullable=False,
            comment="ID of the data source (e.g., arXiv, PubMed)",
        ),
        sa.Column(
            "name",
            sa.Text(),
            nullable=False,
            comment="Name of the domain, e.g., Computer Science, Physics",
        ),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("datasource_id", "code", name="uq_domains_datasource_code"),
    )
    op.create_index(
        op.f("ix_domains_datasource_id"), "domains", ["datasource_id"], unique=False
    )
    op.create_table(
        "paper_ingestion_state",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
            comment="Unique identifier for the paper ingestion state",
        ),
        sa.Column(
            "cursor_date",
            sa.Date(),
            nullable=True,
            comment="Date of the last cursor update",
        ),
        sa.Column(
            "datasource_id",
            sa.UUID(),
            nullable=False,
            comment="ID of the data source (e.g., arXiv, PubMed)",
        ),
        sa.Column(
            "domain_id",
            sa.UUID(),
            nullable=False,
            comment="ID of the domain (e.g., Physics)",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "datasource_id", "domain_id", name="uq_domain_datasource_paper_state"
        ),
    )
    op.create_index(
        op.f("ix_paper_ingestion_state_datasource_id"),
        "paper_ingestion_state",
        ["datasource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_ingestion_state_domain_id"),
        "paper_ingestion_state",
        ["domain_id"],
        unique=False,
    )
    op.create_table(
        "papers",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier for the paper"
        ),
        sa.Column(
            "abstract", sa.Text(), nullable=False, comment="Abstract of the paper"
        ),
        sa.Column(
            "datasource_id",
            sa.UUID(),
            nullable=False,
            comment=(
                "ID of the source from which this paper was "
                "ingested (e.g., arXiv, PubMed)"
            ),
        ),
        sa.Column(
            "domain_id",
            sa.UUID(),
            nullable=False,
            comment=(
                "ID of the high-level academic domain"
                " (e.g., Computer Science, Physics)"
            ),
        ),
        sa.Column(
            "main_author_id",
            sa.UUID(),
            nullable=False,
            comment="ID of the main/primary author of the paper",
        ),
        sa.Column(
            "publish_date", sa.Date(), nullable=False, comment="Date of publication"
        ),
        sa.Column("title", sa.Text(), nullable=False, comment="Title of the paper"),
        sa.Column(
            "paper_identifier",
            sa.String(),
            nullable=False,
            comment="Permanent URL or DOI of the paper",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["main_author_id"],
            ["authors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "domain_id",
            "datasource_id",
            "paper_identifier",
            name="uq_domain_datasource_paper_identifier",
        ),
        sa.UniqueConstraint("paper_identifier"),
    )
    op.create_table(
        "subjects",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Unique identifier for the primary subject",
        ),
        sa.Column(
            "code",
            sa.Text(),
            nullable=False,
            comment="Code for the primary subject, e.g., CS, Physics",
        ),
        sa.Column(
            "domain_id",
            sa.UUID(),
            nullable=False,
            comment="ID of the high-level academic domain (e.g. Physics)",
        ),
        sa.Column(
            "name",
            sa.Text(),
            nullable=False,
            comment="Name of the primary subject, e.g., Physics",
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "domain_id", name="uq_domain_subject_code"),
    )
    op.create_table(
        "paper_authors",
        sa.Column(
            "author_id", sa.UUID(), nullable=False, comment="Reference to Author ID"
        ),
        sa.Column(
            "paper_id", sa.UUID(), nullable=False, comment="Reference to Paper ID"
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("author_id", "paper_id"),
        comment=(
            "Association table to represent many-to-many relationship "
            "between Papers and Authors"
        ),
    )
    op.create_table(
        "paper_subjects",
        sa.Column(
            "is_primary", sa.Boolean(), nullable=False, comment="Primary subject flag"
        ),
        sa.Column(
            "paper_id", sa.UUID(), nullable=False, comment="Reference to Paper ID"
        ),
        sa.Column(
            "subject_id", sa.UUID(), nullable=False, comment="Reference to Subject ID"
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("paper_id", "subject_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paper_subjects")
    op.drop_table("paper_authors")
    op.drop_table("subjects")
    op.drop_table("papers")
    op.drop_index(
        op.f("ix_paper_ingestion_state_domain_id"), table_name="paper_ingestion_state"
    )
    op.drop_index(
        op.f("ix_paper_ingestion_state_datasource_id"),
        table_name="paper_ingestion_state",
    )
    op.drop_table("paper_ingestion_state")
    op.drop_index(op.f("ix_domains_datasource_id"), table_name="domains")
    op.drop_table("domains")
    op.drop_table("datasources")
    op.drop_table("authors")
    # ### end Alembic commands ###
