"""db constraints fix.

Revision ID: 5f42a94447ae
Revises: 5d6a01854542
Create Date: 2026-03-11 14:45:12.501055

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5f42a94447ae"
down_revision: Union[str, Sequence[str], None] = "5d6a01854542"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "domains",
        "code",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_comment="Code for the domain, e.g., CS, Physics",
    )
    op.drop_constraint(op.f("papers_paper_identifier_key"), "papers", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("papers_paper_identifier_key"),
        "papers",
        ["paper_identifier"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "domains",
        "code",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_comment="Code for the domain, e.g., CS, Physics",
    )
    # ### end Alembic commands ###
