"""Create Tables.

Created Papers, Authors, Paper Authors m2m mapping table,
Domain, Source tables.
No index created except default on primary keys

Revision ID: 655f55e76d82
Revises:
Create Date: 2025-12-07 00:48:26.700101

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "655f55e76d82"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier for the author"
        ),
        sa.Column(
            "name", sa.String(), nullable=False, comment="Full name of the author"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "domains",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Unique identifier for the academic domain",
        ),
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
            comment="Description of the domain",
        ),
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
            comment="Name of the domain, e.g., Computer Science, Physics",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sources",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Unique identifier for the data source (e.g., arXiv, PubMed)",
        ),
        sa.Column("name", sa.String(), nullable=False, comment="Name of the source"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "papers",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier for the paper"
        ),
        sa.Column(
            "main_author_id",
            sa.UUID(),
            nullable=False,
            comment="ID of the main/primary author of the paper",
        ),
        sa.Column(
            "domain_id",
            sa.UUID(),
            nullable=False,
            comment=(
                "ID of the high-level academic domain "
                "(e.g., Computer Science, Physics)"
            ),
        ),
        sa.Column(
            "primary_subject",
            sa.String(),
            nullable=False,
            comment="Primary subject area within the domain",
        ),
        sa.Column(
            "secondary_subject",
            sa.String(),
            nullable=True,
            comment=("Secondary subject area within the domain," " if any"),
        ),
        sa.Column(
            "source_id",
            sa.UUID(),
            nullable=False,
            comment=(
                "ID of the source from which this paper"
                " was ingested (e.g., arXiv, PubMed)"
            ),
        ),
        sa.Column("title", sa.String(), nullable=False, comment="Title of the paper"),
        sa.Column(
            "url",
            sa.String(),
            nullable=False,
            comment="Permanent URL or DOI of the paper",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["main_author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "paper_authors",
        sa.Column(
            "author_id", sa.UUID(), nullable=False, comment="Reference to Author ID"
        ),
        sa.Column(
            "paper_id", sa.UUID(), nullable=False, comment="Reference to Paper ID"
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("author_id", "paper_id"),
        comment=(
            "Association table to represent many-to-many "
            "relationship between Papers and Authors"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paper_authors")
    op.drop_table("papers")
    op.drop_table("sources")
    op.drop_table("domains")
    op.drop_table("authors")
    # ### end Alembic commands ###
