"""ingestion state table.

Revision ID: 9d3bdbde9b69
Revises: 3b9f0efd76ba
Create Date: 2026-02-10 22:04:25.811309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9d3bdbde9b69"
down_revision: Union[str, Sequence[str], None] = "3b9f0efd76ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_ingestion_state",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
            comment="Unique identifier for the paper ingestion state",
        ),
        sa.Column(
            "cursor_date",
            sa.Date(),
            nullable=True,
            comment="Date of the last cursor update",
        ),
        sa.Column(
            "datasource_id",
            sa.UUID(),
            nullable=False,
            comment="ID of the data source (e.g., arXiv, PubMed)",
        ),
        sa.Column(
            "domain_id",
            sa.UUID(),
            nullable=False,
            comment="ID of the domain (e.g., Physics)",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paper_ingestion_state_datasource_id"),
        "paper_ingestion_state",
        ["datasource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_ingestion_state_domain_id"),
        "paper_ingestion_state",
        ["domain_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_paper_ingestion_state_domain_id"), table_name="paper_ingestion_state"
    )
    op.drop_index(
        op.f("ix_paper_ingestion_state_datasource_id"),
        table_name="paper_ingestion_state",
    )
    op.drop_table("paper_ingestion_state")
    # ### end Alembic commands ###
