"""Added publish_date.

Revision ID: d261392cb3cf
Revises: 655f55e76d82
Create Date: 2025-12-07 14:30:38.635020

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d261392cb3cf"
down_revision: Union[str, Sequence[str], None] = "655f55e76d82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "papers",
        sa.Column(
            "publish_date", sa.Date(), nullable=False, comment="Date of publication"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "publish_date")
    # ### end Alembic commands ###
