"""added processing state and indexing.

Revision ID: fa5016dc4969
Revises: 5f42a94447ae
Create Date: 2026-03-11 15:24:16.547382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fa5016dc4969"
down_revision: Union[str, Sequence[str], None] = "5f42a94447ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_processing_states",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Unique identifier for the paper processing state",
        ),
        sa.Column("paper_id", sa.UUID(), nullable=False, comment="ID of the paper"),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            comment="Status of the paper processing",
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
            comment="Populated when status=failed; cleared on successful retry",
        ),
        sa.Column(
            "retry_count",
            sa.Integer(),
            nullable=False,
            comment="Number of times this paper has been retried after failure",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paper_processing_states_paper_id"),
        "paper_processing_states",
        ["paper_id"],
        unique=True,
    )
    op.create_index(
        "ix_processing_paper_id",
        "paper_processing_states",
        ["paper_id"],
        unique=False,
        postgresql_using="hash",
    )
    op.create_index(
        "ix_ingestion_datasource_id",
        "paper_ingestion_state",
        ["datasource_id"],
        unique=False,
        postgresql_using="hash",
    )
    op.create_index(
        "ix_ingestion_domain_id",
        "paper_ingestion_state",
        ["domain_id"],
        unique=False,
        postgresql_using="hash",
    )
    op.create_index(
        "ix_papers_datasource_domain",
        "papers",
        ["datasource_id", "domain_id"],
        unique=False,
    )
    op.create_index(
        "ix_papers_datasource_id",
        "papers",
        ["datasource_id"],
        unique=False,
        postgresql_using="hash",
    )
    op.create_index(
        "ix_papers_domain_id",
        "papers",
        ["domain_id"],
        unique=False,
        postgresql_using="hash",
    )
    op.create_index(
        "ix_papers_main_author_id",
        "papers",
        ["main_author_id"],
        unique=False,
        postgresql_using="hash",
    )
    op.create_index("ix_papers_publish_date", "papers", ["publish_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_papers_publish_date", table_name="papers")
    op.drop_index(
        "ix_papers_main_author_id", table_name="papers", postgresql_using="hash"
    )
    op.drop_index("ix_papers_domain_id", table_name="papers", postgresql_using="hash")
    op.drop_index(
        "ix_papers_datasource_id", table_name="papers", postgresql_using="hash"
    )
    op.drop_index("ix_papers_datasource_domain", table_name="papers")
    op.drop_index(
        "ix_ingestion_domain_id",
        table_name="paper_ingestion_state",
        postgresql_using="hash",
    )
    op.drop_index(
        "ix_ingestion_datasource_id",
        table_name="paper_ingestion_state",
        postgresql_using="hash",
    )
    op.drop_index(
        "ix_processing_paper_id",
        table_name="paper_processing_states",
        postgresql_using="hash",
    )
    op.drop_index(
        op.f("ix_paper_processing_states_paper_id"),
        table_name="paper_processing_states",
    )
    op.drop_table("paper_processing_states")
    # ### end Alembic commands ###
