"""ADD subject, paper_subject tables.

Revision ID: fe6e36ec75c8
Revises: d261392cb3cf
Create Date: 2025-12-22 00:28:41.868788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fe6e36ec75c8"
down_revision: Union[str, Sequence[str], None] = "d261392cb3cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subjects",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Unique identifier for the primary subject",
        ),
        sa.Column(
            "code",
            sa.String(length=25),
            nullable=False,
            comment="Code for the primary subject, e.g., CS, Physics",
        ),
        sa.Column(
            "domain_id",
            sa.UUID(),
            nullable=False,
            comment="ID of the high-level academic domain (e.g. Physics)",
        ),
        sa.Column(
            "name",
            sa.String(length=25),
            nullable=False,
            comment="Name of the primary subject, e.g., Physics",
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "paper_subjects",
        sa.Column(
            "is_primary", sa.Boolean(), nullable=False, comment="Primary subject flag"
        ),
        sa.Column(
            "paper_id", sa.UUID(), nullable=False, comment="Reference to Paper ID"
        ),
        sa.Column(
            "subject_id", sa.UUID(), nullable=False, comment="Reference to Subject ID"
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("paper_id", "subject_id"),
    )
    op.add_column(
        "domains",
        sa.Column(
            "code",
            sa.String(length=25),
            nullable=True,
            comment="Code for the domain, e.g., CS, Physics",
        ),
    )
    op.drop_constraint(op.f("domains_name_key"), "domains", type_="unique")
    op.create_unique_constraint("uq_domain_source_code", "domains", ["name", "code"])
    op.drop_column("domains", "description")
    op.drop_column("papers", "primary_subject")
    op.drop_column("papers", "secondary_subject")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "papers",
        sa.Column(
            "secondary_subject",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Secondary subject area within the domain, if any",
        ),
    )
    op.add_column(
        "papers",
        sa.Column(
            "primary_subject",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Primary subject area within the domain",
        ),
    )
    op.add_column(
        "domains",
        sa.Column(
            "description",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Description of the domain",
        ),
    )
    op.drop_constraint("uq_domain_source_code", "domains", type_="unique")
    op.create_unique_constraint(
        op.f("domains_name_key"),
        "domains",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("domains", "code")
    op.drop_table("paper_subjects")
    op.drop_table("subjects")
    # ### end Alembic commands ###
